// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeWS3hw8tU-Qz8t2MwW2iuSHJvpTO0SuU',
    appId: '1:155135898260:web:ec22a9ae1a55010cb67a81',
    messagingSenderId: '155135898260',
    projectId: 'finalapp-a2935',
    authDomain: 'finalapp-a2935.firebaseapp.com',
    storageBucket: 'finalapp-a2935.appspot.com',
    measurementId: 'G-0BYZPP2QGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0AtolI1UjyD-Z60gX58PcHxtU68xmolI',
    appId: '1:155135898260:android:9b140b24617da9e7b67a81',
    messagingSenderId: '155135898260',
    projectId: 'finalapp-a2935',
    storageBucket: 'finalapp-a2935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhR20ksakjYhTew-_hClF2jjtzDm4ZgvQ',
    appId: '1:155135898260:ios:7aafbf6b226e6d4eb67a81',
    messagingSenderId: '155135898260',
    projectId: 'finalapp-a2935',
    storageBucket: 'finalapp-a2935.appspot.com',
    iosClientId: '155135898260-ukcrjp1bmuh3dl2vjm61s8igqrmpvqug.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalapp',
  );

}